apiVersion: v1
kind: Namespace
metadata:
  name: cronx

---
# MySQL PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: cronx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard # For Kind Cluster

---
# Redis PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: cronx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard # For Kind Cluster

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: cronx
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: cronx
spec:
  ports:
    - port: 6379
  selector:
    app: redis
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: cronx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "cronx"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql  # MySQL 数据目录
          ports:
            - containerPort: 3306
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: cronx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          command: [ "redis-server", "--appendonly", "yes", "--requirepass", "cronx" ]
          volumeMounts:
            - name: redis-storage
              mountPath: /data  # Redis 数据目录
          ports:
            - containerPort: 6379
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
