version: "3"

services:
  mariadb:
    image: mariadb:11.4
    container_name: sql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - sql_mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - sql

volumes:
  sql_mariadb_data:
    driver: local

networks:
  sql:
    driver: bridge
